### ISSUE TITLE
Not compatible with AppCode 2022.3

### ISSUE THREAD

**Issue by bes** [kuglee/intellij-swift-format#6]
Hi, I would like to try this plugin with AppCode 2022.3

It's not totally clear that this is a plugin for Apple's swift-format tool https://github.com/apple/swift-format

If it is, I am wondering if you could update to latest AppCode and republish?

**Comment by kuglee** [comment]
With JetBrains discontinuing AppCode, I don't really want to waste time on this plugin anymore.

**Comment by bes** [comment]
:(
